### ISSUE TITLE
Same rule multiple models 

### ISSUE THREAD

**Issue by croepha** [maraujop/django-rules#9]
Is this possible? from the documentation its not clear...

**Comment by jjmaestro** [comment]
Hi!

First of all, thank you for your question. I think I know what you mean by "Same rule multiple models" but I would like to ask you to be more verbose with your question.

Could you please explain it a bit better? What is it that you want exactly? Could you provide us with an example of what you can and cannot do right now?

Thanks so much in advanced!

Regards,

**Comment by croepha** [comment]
Hey, I am still doing preliminary research to see if this will best suit my needs, so I have yet to try this out, but from the docs where it describes what a codename is: "The name of the rule, unique across all applications. It should be a brief but distinctive name" it seems to imply that you must have a different codename for each rule, but I was thinking about extending the existing admin permissions, such as, can_view and using django-rules to implement my own business logic...

can you do something like this?

``` python
django_rules.utils.register(app_name='my_app', codename='can_view', model='SomeModel') 
django_rules.utils.register(app_name='my_app', codename='can_view', model='OtherModel')
django_rules.utils.register(app_name='my_app', codename='can_view', model='YetAnotherModel')
```

Thanks
--Dave

**Comment by jjmaestro** [comment]
Hi Dave,

As you mention in your explanation, right now it's impossible to do what you want because of the uniqueness constraint of the codename that forces you to have a different codename for each rule.

When I asked you to elaborate more on your question, I thought you would probably go along this route so I started developing a patch that fixes this completely: the uniqueness will be enforced at the tuple (codename, model) :)

As such, you will be able to do:

``` python
django_rules.utils.register(app_name='my_app', codename='can_view', model='SomeModel')
django_rules.utils.register(app_name='my_app', codename='can_view', model='OtherModel')
django_rules.utils.register(app_name='my_app', codename='can_view', model='YetAnotherModel')
```

or better, a more compact definition:

``` python
django_rules.utils.register(app_name='my_app', codename='can_view', model=['SomeModel', 'OtherModel', 'YetAnotherModel'])
```

I will discuss it with @maraujop and will try to get this issue closed ASAP.

Thanks!

**Comment by croepha** [comment]
Thanks

**Comment by jjmaestro** [comment]
Dave,

Please have a look at my django-rules fork (https://github.com/jjmaestro/django-rules). The last commit implements the fix that will enable the "one rule, multiple models" feature that you need.

Here is the commit: https://github.com/jjmaestro/django-rules/commit/659901ac9e28eb3de9511ea1fe6652a9bdd6745e

Please tell me if it's OK and if so, we will merge it into the official repo (maraujop's django-rules)

Thanks!

**Comment by jjmaestro** [comment]
Dave,

Have you been able to check my branch with the fix that will enable the "one rule, multiple models" feature that you needed?

Please tell me ASAP because I would like to close this issue. If I don't see an answer any time soon, I will bring the changes from my fork over to the main trunk and will close the issue.

Cheers,

**Comment by croepha** [comment]
Sorry, I havn't gotten back to you, I haven't had a chance to work on this project much lately, Actually I think that I'm going to have to come up with my own authentication backend for what I'm currently doing

Thanks again for helping me answer this question

**Comment by jjmaestro** [comment]
OK, I will keep improving the patch and will probably add it to the trunk repo soon.

Also, I would like to know what kind of stuff you need that django-rules does not cover, because I would like to consider adding that special stuff if it looks good enough! Please just list me a few requirements or project needs that django-rules does not have right now.

Thanks again!

**Comment by croepha** [comment]
well admin integration is a big one... toward that end, it would be necessary to build query-sets based on permissions

**Comment by jjmaestro** [comment]
What do you mean with "Admin integration"? I think we do cover most (if not all) admin permission overrides through our "Centralized Permissions".

Please have a look at the "Centralized Permissions" section in the README and tell me if it would need some additions, I will be happy to have a look at them ;)

Thanks!

**Comment by maraujop** [comment]
He means, having the ability to remove/add/edit the rules using Django admin site, nothing related to admin permissions. 

That is not going to be easy, I'm already thinking it :)

**Comment by jjmaestro** [comment]
Oh, I see! Integration with Django Admin! Well... re-write a whole authorization backend just because you want django admin interface to work instead of hacking it on top of django-rules... I think it would be a bit of an overkill! :-?

Anyways, I would really like a "Wishlist" issue open with a list of desirable stuff in django-rules :)

**Comment by croepha** [comment]
Actually jjmaestro's initial assumption was correct, based on what I read in the README, initially I did not think that it would do admin permissions out of the box... to clarify, this is what I have done thus far:

_disclaimer: this is by no means an example of what someone should do, this just works.   This code does not actually offer security, just obscurity, someone could easily bypass this through their http client_

``` python

# admin.py
class OwnerGroupFilterMixin(object):
    protected_fields = [
        # overide this on a per ModelAdmin basis...
    ]
    def queryset(self, request):
        qs = super(GroupOwnerFilterMixin, self).queryset(request)
        if request.user.is_superuser:
            return qs
        else:
            return qs.filter(owner_group__in=request.user.groups.all())
    def formfield_for_foreignkey(self, db_field, request, **kwargs):
        if not request.user.is_superuser:
            if db_field.name == "owner_group":
                kwargs["queryset"] = request.user.groups
            elif db_field.name in self.protected_fields:
                kwargs["queryset"] = db_field.rel.to.objects.filter(
                  owner_group__in=request.user.groups.all()
                )
        return super(
          GroupOwnerFilterMixin, self
        ).formfield_for_foreignkey(
          db_field,request, **kwargs
        )
    def formfield_for_manytomany(self, db_field, request, **kwargs):
        if (
          not request.user.is_superuser and
          db_field.name in self.protected_fields
        ):
            kwargs["queryset"] = db_field.rel.to.objects.filter(
                owner_group__in=request.user.groups.all()
            )
        return super(
          GroupOwnerFilterMixin, self
        ).formfield_for_manytomany(
          db_field,request, **kwargs
        )

# models.py
class OwnerGroupAbstractModel(django.db.models.Model):
  class Meta:
      abstract = True
  owner_group = models.ForeignKey(django.contrib.auth.models.Group)

```

The business logic: There are certain objects that have a owner_group field, that points to django.contrib.auth.models.Group, users are able to view the objects if they are in the group that owns those objects.

Does django-rules' admin integration cover the change_list view, foreign key and many to many fields?

**Comment by jjmaestro** [comment]
Dave,

I'm a bit confused because it seems to me that you are mixing into this the Admin site support (which we don't have right now) with what django-rules does (per-object authorizations in your app) and with django-rules' support for Central Permissions.

With respect to the latter, please note that central rules are for _all_ objects and from your business logic, you clearly state that it will only apply to _certain_ objects (those with a `owner_group` field). Thus, I would not try to use central permissions.

Now, as of this version of django-rules, we don't have support for the Admin site features that you mention. But since it seems to me that you are just trying to centralize the privacy checks in one place, you can probably do just what you are doing with Abstract base classes, etc.

Something like:
- Create an Abstract base class that knows how to do those checks. Pretty much like your `OwnerGroupFilterMixin` but with a clear _rule name_, in my case `is_member_of_owner_group`. E.g.:

``` python
from django.db import models
from django.contrib.auth.models import User

class AbstractUberGroupPrivacyCheck(models.Model):
    (...)
    def is_member_of_owner_group(self, user_obj):
        """ 
        Checks if the given user_obj is a member of the group of owners
        specified by the owner_group field in the models that extend
        AbstractUberGroupPrivacyCheck
        """ 
        (... here do the magic calling your queryset, like you do in OwnerGroupFilterMixin)
```
- Then, for those models that you want this check, make sure they extend the Abstract class. E.g.:

``` python
class Item(AbstractUberGroupPrivacyCheck):
    owner_group = models.ForeignKey(django.contrib.auth.models.Group)
```

Then, just use the rule name in your `rules_list` and you are all set:

``` python
rules_list = [ 
    {'codename':'is_member_of_owner_group', 'model':['Item', 'Postcard']},
]
```

Sure, to minimize the noise and to avoid having to add a model to the list everytime a developer writes a new extended model, we could have a feature, something like `modelParent` that would let you specify the class name of the parent. Then, you could just do:

``` python
rules_list = [ 
    {'codename':'is_member_of_owner_group', 'modelParent':'AbstractUberGroupPrivacyCheck'},
]
```

I'll think about that ;)

Please tell me if this is enough for your needs or if I'm wrong in my assumptions, etc. Again, Admin site support will be another thing I will discuss with @maraujop so don't hesitate to make your point clearer.

Alno, note that I see how the inheritance solution will probably suffer from the tendency to bloat and create inheritance hierarchy madness in cases where great flexibility is required (such as handling authorization permissions sometimes ;). In those cases, I think that object composition would be much more suitable. I am already thinking on a solution in this direction. Once I discuss it with @maraujop, I will let you know.

If you want to elaborate in much detail your needs, just open issues for every feature you think you need, etc, and I will add them to the Wishlist label. This way, we can discuss different stuff in a straight-forward way and see which things can make it to the django-rules codebase :)

Cheers!
